{{- range $name, $route := .Values.grpcRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "backend-service.fullname" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "backend-service.labels" $ | nindent 4 }}
    {{- with $route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml $route.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml $route.hostnames | nindent 4 }}
  rules:
  {{- range $route.rules }}
  - backendRefs:
    {{- toYaml .backendRefs | nindent 4 }}
    {{- with .matches }}
    matches:
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .filters }}
    filters:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
